
time: [null, null]
lat: [-90, 90]
lon: [-180, 180]
cls: DataArray

cfg:
  fns:
    - _target_: "xarray.${....cls}.sel"
      _partial_: True
      indexers: {time: {_target_: builtins.slice, _args_: '${......time}'}}
    - _target_: "oceanbench._src.geoprocessing.subset.where_slice"
      _partial_: True
      variable: "lat"
      min_val: ${....lat.0}
      max_val: ${....lat.1}
    - _target_: "oceanbench._src.geoprocessing.subset.where_slice"
      _partial_: True
      variable: "lon"
      min_val: ${....lon.0}
      max_val: ${....lon.1}

defaults:
  - /processing/pipe@cfg
