#@package _global_
method: bfn

outputs:
  eval_ds:
    _target_: oceanbench._src.datasets.utils.stack_dataarrays
    _partial_: true
    dataarrays: 
        ref: '${results.outputs.eval.ref}'
        study: '${oc.select:results.outputs.eval.methods.${method}}'
    ref_var: ref
    
  build_eval_ds:
      inp: ${..eval_ds}
      fns: 
          - ${F.call}
          - {_target_: "xarray.DataArray.to_dataset",  dim: 'variable', _partial_: true}
          - {_target_: "xarray.Dataset.map", _partial_: true, func: '${psd_prepro.cfg}'}

  summary: ${metrics.outputs.summary}

  plot_ds:
    maps:
      _target_: oceanbench._src.datasets.utils.stack_dataarrays
      _partial_: true
      dataarrays: 
          ref: '${results.outputs.plots.maps.ref}'
          study: '${oc.select:results.outputs.plots.maps.methods.${method}}'
  plots:
    build_ds:
      maps:
        inp: ${....plot_ds.maps}
        fns:
          - ${F.call}
          - {_target_: "xarray.DataArray.to_dataset",  dim: 'variable', _partial_: true}
    maps: ${maps.outputs.plots}

metrics:
  outputs:
    summary:
      method: '${method}'
      task: ${task.outputs.name}

hydra:
  sweeper:
      params:
          method: {_target_: builtins.str.join, _args_: [',', '${oc.dict.keys:results.outputs.methods}']}

results: ???
task: ???

defaults:
  - /metrics/osse_gf@metrics
  - /funcs@_global_.F
  - /processing/components/grid_psd_prepro@psd_prepro
  - /processing/lib@lib.processing
  - /processing/pipe@outputs.build_eval_ds
  - /processing/pipe@outputs.plots.build_ds.maps
  - /processing/pipe@plots_prepro
  - /plots/gfmaps@maps
  - _self_

